// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Api.Modelos;
using Microsoft.EntityFrameworkCore;

using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Api
{
    public partial interface IDeltaContextProcedures
    {
        Task<EMP> consultarEMPID(int ID);
        Task<List<EMP>> consultarEMP(string usu,string pass);
        Task<Dictionary<bool, string>> GuardarTabla(EMP clase);
        Task<List<Login>> QRY_Login(string usuario, string pass, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
  

    }
}
