// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Api.Modelos;
using Microsoft.EntityFrameworkCore;

using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Api
{
    public partial interface IDeltaContextProcedures
    {
        Task<EMP> consultarEMPID(int ID);

        List<SEGUROS> Consultarseguro(int idempresa, string usu, string pass);
        List<T> Consultar<T>(T objeto, string usu, string pass);
        List<T> ConsultarNombreTabla<T>(string Tabla, string usu, string pass);
        List<T> consultarXId<T>(T objeto, string usu,string pass,int idempresa);
        List<T> consultarEMP<T>(T objeto, string usu, string pass, int idempresa);
        List<T> consultaRAW<T>(T objeto, string sentencia, string usu, string pass);
        Task<Dictionary<bool, string>> Guardar<T>(T eMP, string usu, string pass);
        Task<Dictionary<bool, string>> delete<T>(T objeto, string campowhere, string valorwhere, string usu, string pass);
        Task<Dictionary<bool, string>> Update<T>(T objeto, string campowhere, string valorwhere, string usu, string pass);
        Task<Dictionary<bool, string>> Updatecodigostring<T>(T objeto, string campowhere, string valorwhere, string usu, string pass);

        int ConsultarUltimoCODEMP<T>(T objeto, string usu, string pass);
        int ConsultarnumeroUltimoRegistro<T>(T objeto, string campo, string usu, string pass);
        Task<List<Login>> QRY_Login(string usuario, string pass, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        List<MenuDto> MenuPerfilUsuario(int codemp,string usuario, string pass, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        List<T> CallProceduresConsula<T>(T objeto, string sentencia, string usu, string pass);
        DataTable CallProceduresConsulaDT(string sentencia, string usu, string pass);

        Task<DataSet> ConsultarActa(string usuario, string pass, string periodo, int codigo);
        public string SeccionesSeleccionadas(List<string> secciones)
        {
            string codigos = "";

            foreach (var item in secciones)
            {
                int niveldesde = int.Parse(item.Split("*")[0]);
                int nivelhasta = int.Parse(item.Split("*")[1]);
                for (var dn = niveldesde; dn <= nivelhasta; dn++)
                    codigos = codigos + dn.ToString() + ",";
            }
            
            return codigos;
        }
        private const string directorioGuardaAdjuntos_P = "https://administrativo.uedelta.k12.ec/DeltaArchivos/FileActas/ActasRG/";
        private const string ProductTagFormat = "<a class='Adjunto' href='{1}' target='_blank' >{0}</a><br/>";
        public string ConvertirURL(string texto,int codigo)
        {
            if (texto != "")
            {
                var productNames = texto.Split(",");
                return string.Join(string.Empty, productNames.Select(p => string.Format(ProductTagFormat, p, directorioGuardaAdjuntos_P + "actaRG-COD" + codigo + "/" + p)));
            }
            else
                return "";
        }
    }

}
